services:
  # SPARK
  # MASTER
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"  # SPARK UI Port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077    
    networks:
      - spark-network
  # NODE - include as many Spark workers as you want by simply changing the container name 
  spark-worker-1:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g    
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g    
    networks:
      - spark-network

  spark-worker-3:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g   
    networks:
      - spark-network

  spark-worker-4:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-4
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g   
    networks:
      - spark-network

  spark-worker-5:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-5
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker      
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g    
    networks:
      - spark-network

  spark-worker-6:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-6
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker      
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g   
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
