services:  

  # POSTGRESQL
  postgresdb:
    restart: always
    image: postgres:17.2-alpine3.21
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${PREFECT_POSTGRES_DATABASE},${MLFLOW_POSTGRES_DATABASE}
    volumes:
      - E:\docker\volume\postgresql\data:/var/lib/postgresql/data/
      - E:\docker\volume\postgresql\bash:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${POSTGRES_PORT}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  # PGADMIN
  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    restart: always
    depends_on:
      - postgresdb
    networks:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - E:\docker\volume\pgadmin\data:/var/lib/pgadmin

  # PREFECT SERVER API AND UI 
  prefect-server:
    image: prefecthq/prefect:3.1.12.dev4-python3.12
    restart: always
    depends_on:
      - postgresdb
    networks:
      - postgres
      - prefect
      - ballista
    volumes:      
      - E:\docker\volume\prefect\data:/root/.prefect
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_SERVER_ANALYTICS_ENABLED=False
      - PREFECT_LOGGING_SERVER_LEVEL=WARNING      
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:${POSTGRES_PORT}/${PREFECT_POSTGRES_DATABASE}
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    ports:
      - "${PREFECT_PORT}:4200"

  prefect-worker:
    image: prefecthq/prefect:3.1.12.dev4-python3.12
    working_dir: /app
    command: python -m task
    networks:
      - prefect
      - ballista
    volumes:
      - E:\docker\volume\prefect\data:/app
    environment:
      - PREFECT_API_URL=http://prefect-server:${PREFECT_PORT}/api
      - PREFECT_LOGGING_LEVEL=DEBUG
    profiles: ["worker"]
  
  # MINIO
  s3:
    restart: always
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z.fips
    container_name: s3
    volumes:
      - E:\docker\volume\minio\data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - frontend
      - backend
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_ROOT_USER}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  create_buckets:
    image: minio/mc:RELEASE.2024-11-17T19-35-25Z.fips
    container_name: mlflow_create_buckets
    depends_on:
      - s3
    networks:
      - backend
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set s3 http://s3:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      if /usr/bin/mc stat s3/${MLFLOW_BUCKET_NAME} >/dev/null 2>&1; then
        echo 'Bucket ${MLFLOW_BUCKET_NAME} already exists';
      else
        /usr/bin/mc mb s3/${MLFLOW_BUCKET_NAME};
        /usr/bin/mc policy set download s3/${MLFLOW_BUCKET_NAME};
      fi;
        exit 0;
      "

  tracking_server:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - postgresdb
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - frontend
      - backend
      - postgres
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_PASSWORD}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:${MINIO_PORT}
      - MLFLOW_S3_IGNORE_TLS=true
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:${POSTGRES_PORT}/${MLFLOW_POSTGRES_DATABASE}
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ETCD
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    restart: always
    command: "etcd -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks:
      - ballista

  # BALLISTA SCHEDULER    
  ballista-scheduler:
    image: ghcr.io/apache/arrow-ballista-standalone:0.12.0-rc4
    container_name: ballista-scheduler  
    restart: always
    environment:
      - RUST_LOG=info
    command: "--cluster-backend etcd --etcd-urls etcd:2379 --bind-host 0.0.0.0"
    ports:
      - "50050:50050"   
    volumes:
      - E:\docker\volume\ballista\data:/data
    depends_on:
      - etcd
    networks:
      - ballista
      - backend
    healthcheck:
      test: ["CMD", "nc", "-z", "ballista-scheduler", "50050"]
      interval: 5s
      timeout: 5s
      retries: 5

  # BALLISTA EXECUTOR
  ballista-executor:
    image: ghcr.io/apache/arrow-ballista-standalone:0.12.0-rc4
    restart: always
    depends_on:
      - ballista-scheduler
    command: "--bind-host 0.0.0.0 --scheduler-host ballista-scheduler --scheduler-connect-timeout-seconds 15"
    deploy:
      replicas: 2   
    environment:
      - RUST_LOG=ballista=info
    volumes:
      - E:\docker\volume\ballista\benchmarks\data:/data    
    healthcheck:
      test: ["CMD", "nc", "-z", "ballista-executor", "50051"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ballista
      - backend

  # BALLISTA CLIENT
  ballista-client:
    image: ghcr.io/apache/arrow-ballista-standalone:0.12.0-rc4    
    command: ["/bin/bash", "-c", "sleep infinity"]
    ports:
      - "50051:50051"
    environment:
      - RUST_LOG=info
    volumes:
      - E:\docker\volume\ballista\benchmarks\data:/data
    depends_on:
      - ballista-scheduler
      - ballista-executor

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  postgres:
    driver: bridge
  prefect:
    driver: bridge
  ballista:
    driver: bridge